ALTER TYPE "ArtifactStatus" ADD VALUE IF NOT EXISTS 'LOCAL_CREATED';
ALTER TYPE "ArtifactStatus" ADD VALUE IF NOT EXISTS 'UPLOAD_PENDING';
ALTER TYPE "ArtifactStatus" ADD VALUE IF NOT EXISTS 'UPLOADING';
ALTER TYPE "ArtifactStatus" ADD VALUE IF NOT EXISTS 'STORAGE_VERIFIED';
ALTER TYPE "ArtifactStatus" ADD VALUE IF NOT EXISTS 'DOWNLOAD_VERIFIED';
