ALTER TABLE "Artifact" ADD COLUMN "optimizationJobId" TEXT;
ALTER TABLE "Artifact" ADD COLUMN "schemaVersion" TEXT;
ALTER TABLE "Artifact" ADD COLUMN "storageProvider" TEXT;
ALTER TABLE "Artifact" ADD COLUMN "network" TEXT;
ALTER TABLE "Artifact" ADD COLUMN "storageMode" TEXT;
ALTER TABLE "Artifact" ADD COLUMN "indexerHost" TEXT;
ALTER TABLE "Artifact" ADD COLUMN "rootHash" TEXT;
ALTER TABLE "Artifact" ADD COLUMN "transactionHash" TEXT;
ALTER TABLE "Artifact" ADD COLUMN "contentHash" TEXT;
ALTER TABLE "Artifact" ADD COLUMN "byteSize" INTEGER;
ALTER TABLE "Artifact" ADD COLUMN "uploadStatus" TEXT;
ALTER TABLE "Artifact" ADD COLUMN "proofVerificationStatus" TEXT;
ALTER TABLE "Artifact" ADD COLUMN "retryCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Artifact" ADD COLUMN "safeErrorCode" TEXT;
ALTER TABLE "Artifact" ADD COLUMN "safeErrorMessage" TEXT;
ALTER TABLE "Artifact" ADD COLUMN "uploadedAt" TIMESTAMP(3);
ALTER TABLE "Artifact" ADD COLUMN "verifiedAt" TIMESTAMP(3);
ALTER TABLE "Artifact" ADD COLUMN "encryptedManifest" TEXT;
CREATE INDEX "Artifact_workspaceId_optimizationJobId_idx" ON "Artifact"("workspaceId", "optimizationJobId");
CREATE UNIQUE INDEX "Artifact_workspaceId_optimizationJobId_kind_key" ON "Artifact"("workspaceId", "optimizationJobId", "kind");
ALTER TABLE "Artifact" ADD CONSTRAINT "Artifact_optimizationJobId_fkey" FOREIGN KEY ("optimizationJobId") REFERENCES "OptimizationJob"("id") ON DELETE CASCADE ON UPDATE CASCADE;
